# Generated by Django 3.1.7 on 2021-03-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180907_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='send_messages',
        ),
        migrations.AlterField(
            model_name='advuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
